# Generated by Django 5.0.2 on 2024-03-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment_tool", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyassessment",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="audit",
            name="audit_date",
            field=models.DateField(auto_now=True),
        ),
    ]
