# Generated by Django 5.0.2 on 2024-03-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment_tool", "0002_companyassessment_enabled_alter_audit_audit_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditresult",
            name="extra_fields",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companyassessment",
            name="type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("semi_automatic", "Semi-Automatic"),
                    ("automatic", "Automatic"),
                ],
                default="manual",
                max_length=15,
            ),
        ),
    ]
