# Generated by Django 5.0.2 on 2024-03-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment_tool", "0003_auditresult_extra_fields_companyassessment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditresult",
            name="reviewed",
            field=models.BooleanField(default=False),
        ),
    ]
