# Generated by Django 5.0.2 on 2024-03-16 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment_tool", "0005_archimateobject_archimaterelationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="archimateobject",
            name="company",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archimate_objects",
                to="assessment_tool.company",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="archimaterelationship",
            name="company",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archimate_relationships",
                to="assessment_tool.company",
            ),
            preserve_default=False,
        ),
    ]
